# Generated by Django 5.2 on 2025-08-05 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_coursecategory_course_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'Course Categories'},
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='rubric_score',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.coursecategory'),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
